blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.home_view, name='home'),  
    path('p/<slug:slug>/',views.post_detail_view,name='post-detail'),  
    path('post/new/',views.post_create_view,name='post-create'),
    path('post/<int:pk>/update/', views.post_update_view, name='post-update'),  
    path('post/<int:pk>/delete/',views.post_delete_view, name='post-delete'), 
    path('search/nccbuddies/', views.search_view, name='search'), 
    path('like/post',views.like_view,name='like'),
    path('report/post/',views.post_report_view,name='report'),
    path('report/user/',views.user_report_view,name='report-user'),
    path('<str:username>/notifications/',views.notifications_view,name='notifications'),
    path('<str:username>/notifications/update/',views.notifications_update_view,name='notifications-update'),
    path('<str:username>/notifications/count/',views.notifications_unread_count_view,name='notifications-count'),
    path('account/logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),  

]

blog_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

admin.site.site_header = settings.ADMIN_SITE_HEADER


urlpatterns = [
    path('admin/site/', admin.site.urls), 
    path('', include('blog.urls', namespace='blog')), 
    path('account/register/', user_views.register, name='register'),
    path('account/profile-update/',user_views.updateProfile,name='profile-update'),
    path('account/follow-unfollow/<int:pk>/',user_views.userFollowUnfollow,name="follow-unfollow"),
    path('account/password-change/', user_views.change_password, name='change-password'),

    path('account/login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'), 
    path('account/logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),  
    path('account/password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),  
    path('account/password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),  
    path('account/password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),  
    path('account/password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),  
    path('account/community/', include('footer.urls', namespace='community')),
    path('<str:username>/', user_views.profile, name='profile'),
    path('validate/username/', user_views.validate_username,name='validate-username'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'footer.views.error_404_view'

footer/urls.py
from django.urls import path
from . import views

app_name = "community"

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('contribute/', views.contribute, name='contribute'),
    path('sponsor/', views.sponsor, name='sponsor'),
    path('guidelines/', views.guidelines, name='guidelines'),  
    path('about/', views.about, name='about'),  
    path('facts/',views.facts,name='facts')

]

footer/models.py
from django.db import models
from django.utils import timezone

class Contact(models.Model):
	full_name = models.CharField(max_length=30)
	email = models.EmailField()
	message = models.TextField()
	date = models.DateTimeField(default=timezone.now)
	
	def __str__(self):
		return self.full_name

class Facts(models.Model):
	fact = models.TextField()
	date = models.DateTimeField(default=timezone.now)
	def __str__(self):
		return self.fact

class Quote(models.Model):
	quote= models.TextField()
	date = models.DateTimeField(default=timezone.now)
	def __str__(self):
		return self.quote

footer/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
	class Meta:
		model = Contact
		fields = ['full_name','email','message']

footer/views.py
from django.shortcuts import render
from .forms import ContactForm
from django.http import JsonResponse
from .models import Facts
import random
# Create your views here.

def contact(request):

	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			form.save()
			message = "Your Message/Feedback is sent, manager@nccbuddies will contact you soon. Thank You."
			return render(request,'footer/contact.html',{'message':message})
	else:
		form = ContactForm()
		context = {'form':form}
		return render(request,'footer/contact.html',context)

def contribute(request):
	return render(request,'footer/contribute.html')

def sponsor(request):
	return render(request,'footer/sponsor.html')

def guidelines(request):
	return render(request,'footer/guidelines.html')

def about(request):
	return render(request,'footer/about.html')

def facts(request):
	facts = Facts.objects.all()
	facts_list = []
	for fact in facts:
		facts_list.append(fact.fact)
	random_facts = random.sample(facts_list, 3)
	data = {

		'facts':random_facts

	}
	return JsonResponse(data)
	

def error_404_view(request,exception):
	return render(request,'footer/404.html')

footer/templates/footer/about.html
{% extends "blog/base.html" %}
 {% block title %}
   <title>About - NCC BUDDIES</title> 
 {% endblock %}
{% block content %}
<div class="content-section">
	<h1>About</h1>
	<p>The sole aim of <i>nccbuddy.com</i> is to provide a platform to cadets for sharing and getting knowledge.</p>
	<p>It helps connects NCC cadets and provides a platform where cadets can share their experience, knowledge, memories, and much more.</p>
	<p>We are committed to building a better NCC community by providing a fast and secure platform.</p>
	<p>nccbuddy.com is developed in India.</p>
</div>
{% endblock content %}

footer/templates/footer/contact.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %} 
 {% block title %}
   <title>Contact - Round</title> 
 {% endblock %}
 {% block content %}

<div class="content-section">

	{% if message %}
		<p>{{message}}</p>
	{% else %}
		<form method="POST">
	        {% csrf_token %}
	        <fieldset class="form-group">
	            <legend class="border-bottom mb-4">Contact</legend>
	            <p>Message, Quries and Feedbacks are welcome.</p>
	            {{ form|crispy }}
	        </fieldset>
	        <div class="form-group">
	            <button class="btn btn-outline-info btn-sm" type="submit">Send</button>
	        </div>
	    </form>
	{% endif %}
</div>

{% endblock content %}

footer/templates/footer/contribute.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %} 
 {% block title %}
   <title>Contribute - nccbuddy.com</title> 
 {% endblock %}
 {% block content %}

<div class="content-section">

	<h1>Contribute</h1>
	<ul>
		<li>nccbuddy.com is actively looking for contributors 
			 in various areas mentioned below
			<ol>
				<li>Web Developers or Designers</li>
				<li>Graphics Designers</li>
				<li>Artists</li>
				<li>Content Writers</li>
				<li>In other way you can.</li>
			</ol>
		</li>
		<li>To contribute mail us at nccbuddiesofficial@gmail.com.</li>
		<li>Please be specific in your mail and attach past work samples also.</li>
	</ul>

</div>

{% endblock content %}

footer/templates/footer/guidelines.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %} 
 {% block title %}
   <title>Guideline - "Round"</title> 
 {% endblock %}
 {% block content %}
<style>
.content-section{
	color: #0b4772;
}	
</style>
<div class="content-section">

	<h1>Guidelines</h1>
	<p>By posting on "Round", you are agreeing to abide by the following community guidelines (‘Guidelines’). Although we will do our utmost to avoid this, "Round" reserves the right to delete, move or otherwise alter posts posted by users if they are deemed to violate these guidelines.</p>
   <ul>	 
   		<li>Usernames, posts and profile-info must not contain any profane, offensive, or derogatory terms</li>
   		<li>Posting of advertisements, promotions, and spam is prohibited</li>
   		<li>Please don’t post knowingly offensive slurs and discriminatory posts based on race, ethnicity, gender, physical and mental ability, sexual orientation, religion, culture, beliefs or politics. Derogatory statements of any kind are not allowed</li>
   		<li>No threats of any kind, personal attacks, or harassment</li>
   		<li>Do not encourage others to violate laws or harm property or people</li>
   		<li>Profanity is prohibited—whether blatant or censored with special characters</li>
   		<li>No inflammatory or libelous statements are alloweds</li>
   		<li>No unlawful content (local, state, or central) is allowed to be posted or linked to</li>
   		<li>Please don’t impersonate anyone or misrepresent yourself</li>
   		<li>Don’t post any medical advice, or accept any medical advice from other users</li>
   		<li>Don’t upload, post, transmit, or make available, any material that contains viruses or any other computer code, programs or files designed to destroy, interrupt, or limit the functionality of any computer software or hardware or telecommunications equipment.</li>

   		<p>Please alert "Round" if you see offensive language, abusive language, spam, self-promotion or advertising, or off-topic posts. The "Round" will take measures to ensure that questionable posts are removed if they violate the community guidelines.<br>
   		<small><a href="{% url 'community:contact' %}">click here</a> to contact.</small>
   		</p>
   </ul>

</div>

{% endblock content %}

footer/templates/footer/sponsor.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %} 
 {% block title %}
   <title>Sponsor - "Round"</title> 
 {% endblock %}
 {% block content %}

<div class="content-section">

	<h1>Sponsor</h1>
	<ul>
		<li>For sponsoring and ads contact us(<a href="{% url 'community:contact' %}">click here</a>).
		</li>
	</ul>

</div>

{% endblock content %}