blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.home_view, name='home'),  
    path('p/<slug:slug>/',views.post_detail_view,name='post-detail'),  
    path('post/new/',views.post_create_view,name='post-create'),
    path('post/<int:pk>/update/', views.post_update_view, name='post-update'),  
    path('post/<int:pk>/delete/',views.post_delete_view, name='post-delete'), 
    path('search/nccbuddies/', views.search_view, name='search'), 
    path('like/post',views.like_view,name='like'),
    path('report/post/',views.post_report_view,name='report'),
    path('report/user/',views.user_report_view,name='report-user'),
    path('<str:username>/notifications/',views.notifications_view,name='notifications'),
    path('<str:username>/notifications/update/',views.notifications_update_view,name='notifications-update'),
    path('<str:username>/notifications/count/',views.notifications_unread_count_view,name='notifications-count'),
    path('account/logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),  

]

blog_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

admin.site.site_header = settings.ADMIN_SITE_HEADER


urlpatterns = [
    path('admin/site/', admin.site.urls), 
    path('', include('blog.urls', namespace='blog')), 
    path('account/register/', user_views.register, name='register'),
    path('account/profile-update/',user_views.updateProfile,name='profile-update'),
    path('account/follow-unfollow/<int:pk>/',user_views.userFollowUnfollow,name="follow-unfollow"),
    path('account/password-change/', user_views.change_password, name='change-password'),

    path('account/login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'), 
    path('account/logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),  
    path('account/password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),  
    path('account/password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),  
    path('account/password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),  
    path('account/password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),  
    path('account/community/', include('footer.urls', namespace='community')),
    path('<str:username>/', user_views.profile, name='profile'),
    path('validate/username/', user_views.validate_username,name='validate-username'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'footer.views.error_404_view'

footer/urls.py
from django.urls import path
from . import views

app_name = "community"

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('contribute/', views.contribute, name='contribute'),
    path('sponsor/', views.sponsor, name='sponsor'),
    path('guidelines/', views.guidelines, name='guidelines'),  
    path('about/', views.about, name='about'),  
    path('facts/',views.facts,name='facts')

]

users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


from PIL import Image
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill,Transpose
from taggit.managers import TaggableManager


WING = [
    
    ('ARMY','ARMY'),
    ('NAVAL','NAVAL'),
    ('AIR FORCE','AIR FORCE')
    
]

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=25,blank=True)
    image = models.ImageField(default='default.png', upload_to='profile_pics')
    image_thumbnail_user = ImageSpecField(source='image',
                                      processors=[Transpose(),ResizeToFill(170, 170)],
                                      format='JPEG',
                                      options={'quality': 100})

    description = models.CharField(max_length=100, blank=True)
    follows = models.ManyToManyField(User,related_name="follows",blank=True)
    followers = models.ManyToManyField(User,related_name="followers",blank=True)
    camps = TaggableManager(blank=True)
    wing = models.CharField(max_length=10,choices=WING,blank=True)
    def __str__(self):
        return f"{self.user.username}'s Profile"



REASON = [
    
    ('SPAM','SPAM'),
    ('INAPPROPRIATE','INAPPROPRIATE'),
    
]


class UserReport(models.Model):
    reported_user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='reported_user')
    reason = models.CharField(max_length=10,choices=REASON)
    reporting_user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='reporting_user')
    date_reported = models.DateTimeField(default=timezone.now) 

    def __str__(self):
        return self.reported_user.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

from .models import Profile, UserReport


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    camps = TaggableManager(verbose_name=u'Pasta')
    class Meta:
        model = Profile
        fields = ['image','name','description','wing','camps']


class ReportUserForm(forms.ModelForm):
    class Meta:
        model = UserReport
        fields = ['reason']

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm,ReportUserForm
from blog.models import Post, Notification
from django.contrib.auth.models import User
from django.http import JsonResponse


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created!\
                            You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    
    context = {'form': form}
    template_name = 'users/register.html'
    
    return render(request, template_name, context)

def validate_username(request):
    username = request.GET.get('username',None)
    data = {
        'is_taken':User.objects.filter(username__iexact=username).exists()
    }
    print(data)
    return JsonResponse(data)


# @login_required
def profile(request,username=None):
    report_form = ReportUserForm()
    user =  get_object_or_404(User,username=username)
    post_list = Post.objects.filter(author=user).order_by('-id')
    post_count = post_list.count()
    page = request.GET.get('page', 1)
    paginator = Paginator(post_list, 4)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)    
    
    context = {
        'report_form':report_form,
        'posts':posts,
        'user_id':user,
        'post_count':post_count,
    }
    template_name = 'users/profile.html'

    return render(request, template_name, context)

@login_required
def updateProfile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile',username=request.user.username)
        else:
            messages.error(request, f'Username already exists or in use!')
            return redirect('profile-update')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
        context = {
            'u_form': u_form,
            'p_form': p_form,
        }
        template_name = 'users/update_profile.html'

        return render(request, template_name, context)


@login_required
def userFollowUnfollow(request,pk=None):
    current_user = request.user
    other_user = User.objects.get(pk=pk)

    if other_user not in current_user.profile.follows.all():
        current_user.profile.follows.add(other_user)
        other_user.profile.followers.add(current_user)
        
        notify = Notification.objects.create(sender=current_user,receiver=other_user,action="started following you.")

    else:
        current_user.profile.follows.remove(other_user)
        other_user.profile.followers.remove(current_user)
    return redirect('profile',username=other_user.username)


@login_required
def  change_password(request):
    if request.method == 'POST':
        form  =  PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('profile',username=request.user.username)
        else:
            return redirect('change-password')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form':form}
        return render(request, 'users/change_password.html',args)

users/templates/users/change_password.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %} 
{% block title %}<title> @{{request.user.username}} change password - "nccbuddy.com"</title>{% endblock %}

{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Change Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info btn-sm" type="submit">Change</button>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/login.html
{% extends "blog/base.html" %} 
{% load crispy_forms_tags %}
{% block title %}
  <title>Login - "Round"</title>
{% endblock %} 
{% block content %}
<div>
    <small class="text-muted">
        <b>Need An Account?</b> 
        <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
    </small>
</div>
<br>
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info btn-sm" type="submit">Login</button>
            <small class="text-muted ml-2">
                <a href="{% url 'password_reset' %}">Forgot Password?</a>
            </small>
        </div>
    </form>
    <div class="border-top pt-3">
        
    </div>
</div>
<div class="card">
    <div class="card-body">
        <p>You can use Round to:</p>
        <ul>
            <li>Write posts on your Round memories and share knowledge.</li>
            <li>Get to know more Rounders</li>
            <li>Don't have an account yet? <a href="{% url 'register' %}"> Click here</a> to register.</li>
        </ul>
    </div>
</div><br>
{% endblock content %}

users/templates/users/logout.html
 {% extends "blog/base.html" %}
 {% block title %}
  <title>logged out - "nccbuddy.com"</title>
{% endblock %} 
 {% block content %}
<h2>You have been logged out</h2>
<div class="border-top pt-3 pb-3">
    <small class="text-muted">
        <a href="{% url 'login' %}">Log In Again</a>
    </small>
</div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends "blog/base.html" %} \

{% load crispy_forms_tags %} 

{% block title %}
  <title>Password Reset - "nccbuddy.com"</title>
{% endblock %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info btn-sm"
                    type="submit">Request Password Reset</button>
        </div>
    </form>
</div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "blog/base.html" %}
{% block title %}
  <title>Password Reset Done - "nccbuddy.com"</title>
{% endblock %}
{% block content %}

    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a class="btn btn-outline-info btn-sm"  href="{% url 'login' %}">Sign In Here</a>

{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "blog/base.html" %} 
{% load crispy_forms_tags %} 
{% block title %}
  <title>Password Reset Done - "nccbuddy.com"</title>
{% endblock %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info btn-sm"
                    type="submit">Reset Password</button>
        </div>
    </form>
</div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "blog/base.html" %}
{% block title %}
  <title>Password Reset Done - "nccbuddy.com"</title>
{% endblock %}
{% block content %}

    <div class="alert alert-info">
        An email has been sent with instructions to reset your password.
    </div>

{% endblock content %}

users/templates/users/register.html
 {% extends "blog/base.html" %} 
 {% load crispy_forms_tags %} 
 {% block title %}
  <title>Sign Up - nccbuddy.com</title>
{% endblock %}
 {% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create Your Account</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <small>By signing up you are agree to follow Round guidelines (<a href="{% url 'community:guidelines' %}">click here</a> to read)</small>.<br><br>
            <button class="btn btn-outline-info btn-sm" type="submit">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
                <b>Already Have An Account? </b>
                <a class="ml-2" href="{% url 'login' %}">Log In</a>
        </small>
    </div>
</div>
{% endblock content %}


{% block script %}

<script type="text/javascript">
    
    $("#id_username").change(function(){

        var username = $(this).val();

        $.ajax({

            url:'{% url "validate-username" %}',
            data: {
                'username':username
            },
            dataType: 'json',
            success: function(data){
                if (data.is_taken) {
                    alert("Username Already Taken!");
                }
            }

        })

    });

</script>


{% endblock %}

users/templates/users/update_profile.html
{% extends "blog/base.html" %} 
{% load static %}
{% load crispy_forms_tags %} 

{% block title %}<title> @{{request.user.username}} profile update - nccbuddy.com</title>{% endblock %}

{% block content %}
<div class="content-section">
    <form method="POST" enctype="multipart/form-data" id="user-update-form">
        {% csrf_token %}
        <fieldset class="form-group">
            <div class="profile_update border-bottom">
                <legend class="mb-3">Update Profile
                </legend>
            </div>
            {{ u_form|crispy }} 
            {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-info btn-sm" type="submit" id="submit-update-btn">Update</button>
        </div>
    </form>
    <a class="nav-item nav-link" style="position: absolute;right: 25px;bottom: 25px;font-size: 15px;" href="{% url 'logout' %}">Logout</a>
    <div class="border-top pt-3">
        <small class="text-muted">
            <b>Change Password?</b>
            <a class="ml-2" href="{% url 'change-password' %}">click here</a>
        </small>
    </div>
</div>
<div id="loader">
    <p style="position: absolute;top: 50%;right: 50%;color: white">Updating...</p>
</div>
{% endblock content %}

{% block script %}

<script type="text/javascript">
    $(document).ready(function(){
        // $('#div_id_image').children('div').addClass('currentPhoto');
        // $('.currentPhoto').children('a').hide();
        // let isTextNode = (_, el) => el.nodeType === Node.TEXT_NODE;
        // $('.currentPhoto').contents().filter(isTextNode).remove();
        // var img = document.createElement("IMG");
        // img.src = '{{ user.profile.image_thumbnail_user.url }}';
        // img.setAttribute('class', 'account-img');
        // $('.currentPhoto').prepend('<br>Change Image'); 
        // $('.currentPhoto').prepend(img);
        $('#hint_id_camps').html('Add comma between Camps you have attended!');
        $('#div_id_camps label').html('Camps*');

        $('#submit-update-btn').on('click',function(e){
            if ($('#id_username').val()!=="" && $('#id_email').val()!==""){
                $('#loader').show()
            }
            else{
                $('#loader').hide()

            }
        })

    });
</script>
{% endblock %}